# Generated by Django 4.2.2 on 2023-07-25 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=90)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Closed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auction Room',
                'verbose_name_plural': 'Auction Rooms',
            },
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidder_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bidder',
                'verbose_name_plural': 'Bidders',
            },
        ),
        migrations.CreateModel(
            name='AuctionRoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('auctioneer', 'Actioneer'), ('bidder', 'Bidder')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.auctionroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Room User',
                'verbose_name_plural': 'Auction Room Users',
            },
        ),
        migrations.CreateModel(
            name='Auctioneer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auctioneer_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auctioneer',
                'verbose_name_plural': 'Auctioneers',
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Closed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auctioneer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='bidding.auctioneer')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='auctions', to='bidding.bidder')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
            },
        ),
    ]
