# Generated by Django 4.2.2 on 2023-07-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bidding", "0002_alter_auction_id_alter_auctioneer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionroom",
            name="auction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auction_acc",
                to="bidding.auction",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="auctions",
                to="bidding.bidder",
            ),
        ),
    ]
