# Generated by Django 4.1.10 on 2023-08-02 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auctionroom_auction_alter_auction_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('auction_room_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auction Log',
                'verbose_name_plural': 'Auction Logs',
            },
        ),
    ]
